name: CI/CD Pipeline

on:
  push:
    branches:
      - one


jobs:
  create_s3_bucket:
    runs-on: ubuntu-latest
    
    steps:
    

    - name: Checkout repository
      uses: actions/checkout@v3


    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::957271766300:user/Codeorion
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
      working-directory: ./terraform1

    - name: Terraform Init
      id: init
      run: terraform init
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: List files
      run: ls -l ./terraform1

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-colorsa


    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true
  

      - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -input=false
      working-directory: ./terraform1
